# Default Restyler Configuration
#
# All keys are optional and default as shown. All list values can also be given
# a single value, to indicate a single-element list.
#
####

# Do anything at all?
enabled: true

# Patterns to exclude from all Restylers
#
# By default, we ignore directories that are often checked-in but rarely
# represent project code. Some globs are slightly complicated to match paths
# within directories of names appearing at any depth.
#
# This behavior can be disabled in your project with:
#
#   exclude: []
#
exclude: []

# Push the style fixes directly to the original PR
#
# This setting implies pull_requests: false for origin PRs, and has no effect on
# forked PRs (since we can't push to those).
#
auto: false

# Download remote files before restyling
#
# Example:
#
#   remote_files:
#     - url: https://raw.github.com/.../hlint.yaml
#       path: .hlint.yaml
#
# Files must be publicly accessible.
#
remote_files: []

# Open Restyle PRs?
pull_requests: true

# Leave comments on the original PR linking to the Restyle PR?
comments: true

# Set commit statuses?
#
# A single value can be used to disable/enable all:
#
#   statuses: false
#
# Or separate values as shown in the below defaults:
#
statuses:
  # Red status in the case of differences found
  differences: true
  # Green status in the case of no differences found
  no_differences: true
  # Red status if we encounter errors restyling
  error: false

# Request review on the Restyle PR?
#
# Possible values:
#
#   author: From the author of the original PR
#   owner:  From the owner of the base repository
#   none:   Don't
#
# One value will apply to both origin and forked PRs:
#
#   request_review: author
#
# but you can also specify separate values:
#
#   request_review:
#     origin: author
#     forked: owner
#
request_review: author

# Add labels to any created Restyle PRs
#
# These can be used to tell other automation to avoid our PRs.
#
#   labels:
#     - pullassigner-ignore
#
labels: []

# Labels to ignore
#
# PRs with any of these labels will be ignored by Restyled.
#
ignore_labels:
  - restyled-ignore

# Version of the set of Restylers to run
#
# This should correspond to a ref on the restyled-io/restylers repository,
# usually it's a tag that is a date of when that set was released. You could
# re-specify the default in your own config if you prefer to avoid update
# surprises.
#
restylers_version: "20200331"

restylers:
  - dotnet-format
  - prettier-markdown
  - prettier-yaml
  - whitespace