skip_tags: true
image: Visual Studio 2017
configuration: Release

skip_commits:
  message: /\[WIP\]/

install:
  - cinst gitversion.portable
  - nuget restore
  - ps: gitversion /l console /output buildserver

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(GitVersion_FullSemVer)
  package_version: $(GitVersion_FullSemVer)
  assembly_version: $(GitVersion_AssemblySemVer)
  file_version: $(GitVersion_AssemblySemVer)
  informational_version: $(GitVersion_FullSemVer)

on_failure:
  - ps: 7z a "WorkingTree.zip"
  - ps: Push-AppveyorArtifact WorkingTree.zip

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal

deploy:
- provider: GitHub
  auth_token:
    secure: rcCwQSqZnKqRbc012jkvKtUz3/771EcE/Ce/2yL1IA9vhvirOdAmCGxG2yFocFjv
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: Xf37hl3mjjSlD3nyEpdUO9wOfyPU3z1pHqq41WnP0jqviNFJo6FpKC3hOIjwLRb4
  on:
    branch: master